
POST http://localhost:5000/like HTTP/1.1
Content-Type: application/json

{
     "id": "63f3d07c63c36707d752b734",
    "uid": "34"
}
###

POST https://saathi-production.up.railway.app/like HTTP/1.1
Content-Type: application/json

{
     "id": "63f3d07c63c36707d752b734",
    "uid": "3Sl1oXHIMCWixyUyO6RrXoKNiw83"
}
###
GET http://localhost:5000/getLikes?id=63f3d07c63c36707d752b734 HTTP/1.1
